---
- hosts: 127.0.0.1
  connection: local
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: install Microsoft signing key
      rpm_key:
          state: present
          key: https://packages.microsoft.com/keys/microsoft.asc
    - name: install VSCode repository
      copy:
          src: "{{ playbook_dir }}/vscode/vscode.repo"
          dest: /etc/yum.repos.d/vscode.repo
          owner: root
          group: root
          mode: '0644'
    - name: install rpmfusion repositories
      dnf:
          name:
              - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
              - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    - name: ensure packages are installed
      dnf:
          name: >
              bat, 
              cascadia-code-fonts,
              clang,
              cmake,
              code,
              exa,
              fd-find,
              fish,
              fzf,
              gcc-c++,
              gnome-tweaks,
              make,
              neovim,
              ninja-build,
              openssh-server,
              openssl-devel,
              ripgrep,
              starship,
              tmux-powerline,
              tokei,
              util-linux-user
          state: latest
    - name: enable ssh server
      systemd:
          state: started
          enabled: yes
          name: sshd

