---
- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
    - name: make starship.toml link
      file:
          src: "{{ playbook_dir }}/config/starship.toml"
          dest: "/home/{{ ansible_user_id }}/.config/starship.toml"
          state: link
          follow: no
    - name: nvim config link
      file:
          src: "{{ playbook_dir }}/config/nvim"
          dest: "/home/{{ ansible_user_id }}/.config/nvim"
          state: link
          follow: no
    - name: tmux config link
      file:
          src: "{{ playbook_dir }}/tmux.conf"
          dest: "/home/{{ ansible_user_id }}/.tmux.conf"
          state: link
          follow: no
    - name: VSCode user configuration
      file:
          path: "/home/{{ ansible_user_id }}/.config/Code/User"
          state: directory
          owner: "{{ ansible_user_id }}"
          group: "{{ ansible_user_id }}"
          mode: 0755
      file:
          src: "{{ playbook_dir }}/config/Code/settings.json"
          dest: "/home/{{ ansible_user_id }}/.config/Code/User/settings.json"
          state: link
          follow: no
    - name: change shell to fish
      user:
          name: "{{ ansible_user_id }}"
          shell: /usr/bin/fish

