[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome"

[[block]]
block = "music"
player = "mpd"
#buttons = ["play", "prev", "next"]
#max_width = 50
#on_click = "kitty ncmpcpp"

[[block]]
block = "memory"
display_type = "memory"
#format_mem = "{mem_free;G}%"
#format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1
format = "$barchart $utilization"

[[block]]
block = "load"
#interval = 1
format = "1min: $1m"

#[[block]]
#block = "sound"

[[block]]
block = "uptime"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %R"

