[skin]
default = "rgb(255,0,0) none"
tree = "ansi(241) None"                                    # bg3
file = "ansi(223) None"                                    # fg
directory = "ansi(208) None"                               # orange
exe = "ansi(214) None"                                     # yellow
link = "ansi(142) None"                                    # green
pruning = "ansi(243) None"                                 # bg4 ("unlisted xx")
perm__ = "ansi(239) None"                                  # bg2 ("_" in perms)
perm_r = "rgb(215,153,33) None"                            # dark yellow
perm_w = "rgb(204,36,29) None"                             # dark red
perm_x = "rgb(152,151,26) None"                            # dark green
owner = "rgb(215,153,33) None"                             # dark yellow
group = "rgb(215,153,33) None"                             # dark yellow
count = "ansi(109) None"                                   # blue (use --sort-by-count)
dates = "rgb(69,133,136) None"                             # dark blue
sparse = "ansi(167) None"                                  # red (sparse file)
content_extract = "ansi(132) None"                         # dark purple
content_match = "ansi(108) None"                           # aqua
git_branch = "ansi(214) None"                              # yellow
git_insertions = "ansi(106) None"                          # d_green
git_deletions = "ansi(124) None"                           # d_red
# git_status_current = "gray(5) None"                      # ?? (' ')
git_status_modified = "ansi(142) None"                     # green ('M')
git_status_new = "ansi(132) None"                          # purple ('N')
git_status_ignored = "ansi(241) None"                      # bg3 ('I')
git_status_conflicted = "ansi(208) None"                   # orange ('C')
# git_status_other = "ansi(88) None"
# selected_line = "None gray(5) / None gray(4)"
# char_match = "Yellow None"
file_error = "ansi(196) None"                              # bright red (no gruvbox color)
# flag_label = "gray(15) None"
# flag_value = "ansi(208) None Bold"
# input = "White None / gray(15) gray(2)"
# status_error = "gray(22) ansi(124)"
# status_job = "ansi(220) gray(5)"
# status_normal = "gray(20) gray(3) / gray(2) gray(2)"
# status_italic = "ansi(208) gray(3) / gray(2) gray(2)"
# status_bold = "ansi(208) gray(3) Bold / gray(2) gray(2)"
# status_code = "ansi(229) gray(3) / gray(2) gray(2)"
# status_ellipsis = "gray(19) gray(1) / gray(2) gray(2)"
# purpose_normal = "gray(20) gray(2)"
# purpose_italic = "ansi(178) gray(2)"
# purpose_bold = "ansi(178) gray(2) Bold"
# purpose_ellipsis = "gray(20) gray(2)"
# scrollbar_track = "gray(7) None / gray(4) None"
# scrollbar_thumb = "gray(22) None / gray(14) None"
# help_paragraph = "gray(20) None"
# help_bold = "ansi(208) None Bold"
# help_italic = "ansi(166) None"
# help_code = "gray(21) gray(3)"
# help_headers = "ansi(208) None"
# help_table_border = "ansi(239) None"
# preview = "gray(20) gray(1) / gray(18) gray(2)"
# preview_line_number = "gray(12) gray(3)"
# preview_match = "None ansi(29) Underlined"
# hex_null = "gray(10) None"
# hex_ascii_graphic = "gray(18) None"
# hex_ascii_whitespace = "ansi(143) None"
# hex_ascii_other = "ansi(215) None"
# hex_non_ascii = "ansi(167) None"

